# Generated by Django 5.2.1 on 2025-06-05 18:02


from django.db import migrations

def create_admin_user(apps, schema_editor):
    User = apps.get_model('hello', 'CustomUser')
    if not User.objects.filter(username='michelle').exists():
        User.objects.create_superuser('michelle', 'michellelabarre@yahoo.com', 'michelle')


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
