# Generated by Django 5.2.1 on 2025-05-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_comment_user_logmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
