# Generated by Django 5.2.1 on 2025-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_caremessage_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
