# Generated by Django 5.2.3 on 2025-06-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_caremessage_user_caremessage_shared_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremessage',
            name='shared_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_message', to='hello.sharedaccount'),
        ),
    ]
